# Site settings
title:       'Augusto Rückert'
email:       ''
description: 'Digital Product Management'
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://ruckert.com.br/' # The base hostname & protocol for your site
twitter:     'https://twitter.com/ruckert'
github:      'https://github.com/ruckert/'
instagram:   'https://www.instagram.com/augusto.ruckert/'
facebook:    ''

markdown:  kramdown
permalink: pretty
paginate:  10

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext